### ISSUE TITLE
Bonus light not showing on weapon info

### ISSUE THREAD

**Issue by Razac2306** [daemitus/ZodiacBuddy#17]
well the title pretty much says it, unless its something that appears after the bonus light changes duty?
also, would it be possible to have it show in the Zodiac Glass?

**Comment by Hiroa** [comment]
Hello
The Bonus light is discovered by crowdsourcing. So after every reset, someone with the plugin need to find it in order to share the information with the others.
Just to be sure, what is your datacenter ? I'm not sure that we are compatible with the KR and CN servers.
Also, do you have the following option enable ?
![image](https://user-images.githubusercontent.com/3938368/180756277-98d3d0b1-38ea-4623-982f-dbe4c53b94ef.png)

**Comment by Razac2306** [comment]
I do have that turned on
I'm on Elemental
and I had an inkling that it was crowdsourced but wasn't too sure

**Comment by Hiroa** [comment]
Do you still have this issue ?
You can check [here](https://zodiac-buddy-db.fly.dev/reports/active) if there is an active light bonus that has been report.
If there is something between the square brackets, a light bonus has been report and should appear on the plugin.
